Expose the "Should Replace Name" and "Get Replacement Name" functions so they can be accessed via game.cub.hideNames
death-save/combat-utility-belt pull request #693
Opened 2022-07-16 05:08 UTC by Autmor

FEAT: Exposed Replacement Name Functions for intermodule functionality

2022-07-16 05:09 UTC, Autmor commented
Main reason I'm asking this : https://github.com/Autmor/yourTurn/issues/3

2022-07-27 04:56 UTC, eclarke12 requested changes
I like the intent of this PR and it lines up with #621 however, I would prefer to follow the existing API strategy which is to maintain the static methods and simply add a convenience accessor on the `game.cub` object. Please review:
https://github.com/death-save/combat-utility-belt/blob/f0f65a3a69caf3f393f53cd188fe11af02d86515/modules/signal.js#L80

If you'd like to make that change please go ahead, otherwise if I don't hear back in a day or so I will make the change and move forward with the release.

2022-07-27 12:34 UTC, Autmor commented
Ahhh , I see. I'll make that change tonight. Thank you!

2022-07-28 03:16 UTC, eclarke12 approved these changes

2022-07-28 03:16 UTC, merged